CC=gcc
CFLAGS=-Wall -O3
CXX=g++
CXXFLAGS=-std=c++14 -Wall -O3

all: test_some_cipher_2
clean:
	rm some_cipher_2.o test_some_cipher_2
	rm brute_force.o test_brute_force

some_cipher_2.o: some_cipher_2.h
test_some_cipher_2: some_cipher_2.o
