CC=gcc
CFLAGS=-Wall -O3
CXX=g++
CXXFLAGS=-std=c++11 -Wall -O3

all: gen_pairs_1005_450 gen_pairs_1005_540
gen_pairs_1005_450: ../some_cipher.o
gen_pairs_1005_540: ../some_cipher.o
clean:
	rm gen_pairs_1005_450 gen_pairs_1005_540
